name: venvexploration
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10.9
  - pip=22.2.2
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy=1.23.1
  - pandas=1.5.3
  - scikit-learn=1.2.1
  - seaborn=0.12.2
  - matplotlib=3.7.0
  - graphviz=2.50.0
  - python-graphviz=0.20.1
  - pydot=1.4.1
  - pypdf2=2.10.5
  - jupyter=1.0.0
  - tqdm=4.65.0
  - pip:
    - xgboost==1.7.4
    - threadpoolctl==3.1.0
    - rdt==1.3.0
    - plotly==5.13.1
    - iteration_utilities==0.11.0
    - wandb==0.15.0
    - orange3==3.30